name: Ecosystem CI

on:
  issue_comment:
    types: [created]

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/ecosystem-ci run') }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'jotaijs/jotai-ecosystem-ci'
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile
      - id: short_sha
        run: echo "x=${{ github.event.issue.pull_request.head.sha }}" | cut -c1-10 >> $GITHUB_OUTPUT
      - id: run_command
        run: |
          echo "x<<EOF" >> $GITHUB_OUTPUT
          pnpm run ecosystem-ci | grep -A999 -- '---- Jotai Ecosystem CI Results ----' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          JOTAI_PKG: https://pkg.csb.dev/pmndrs/jotai/commit/${{ steps.short_sha.outputs.x }}/jotai
      - uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.pull_request.number }}
          body: |
            ## Ecosystem CI Output
            ```
            ${{ steps.run_command.outputs.x }}
            ```
